DROP TABLE IF EXISTS sys_user_permission;
DROP TABLE IF EXISTS sys_permission;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS document_processing_task;
DROP TABLE IF EXISTS document_segment;
DROP TABLE IF EXISTS document_version;
DROP TABLE IF EXISTS knowledge_document;

CREATE TABLE knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    document_user BIGINT NOT NULL,
    current_version_id BIGINT NOT NULL,
    version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE document_segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    chunk_id BIGINT NOT NULL,
    embedding_id BIGINT,
    skip_embedding TINYINT NOT NULL DEFAULT 0,
    segment_content CLOB NOT NULL,
    metadata CLOB,
    status VARCHAR(32) NOT NULL DEFAULT 'init',
    document_version_id BIGINT NOT NULL,
    segment_index INT NOT NULL,
    token_count INT,
    vector_hash CHAR(64),
    lock_version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id BIGINT NOT NULL UNIQUE,
    document_id BIGINT NOT NULL,
    version_no VARCHAR(32) NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    converted_document_name VARCHAR(255),
    document_path VARCHAR(1024),
    content CLOB,
    document_status VARCHAR(32) NOT NULL DEFAULT 'init',
    document_type VARCHAR(64),
    segment_numbers INT NOT NULL DEFAULT 0,
    source_hash CHAR(64),
    content_hash CHAR(64),
    change_summary VARCHAR(500),
    source_version_id BIGINT,
    document_version_status VARCHAR(32) NOT NULL DEFAULT 'active',
    lock_version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL,
    CONSTRAINT uk_document_version_no UNIQUE (document_id, version_no),
    CONSTRAINT uk_document_version_content UNIQUE (document_id, content_hash),
    CONSTRAINT fk_document_version_document FOREIGN KEY (document_id)
        REFERENCES knowledge_document (document_id)
);

ALTER TABLE document_segment
    ADD CONSTRAINT uk_document_segment_chunk UNIQUE (chunk_id);

ALTER TABLE document_segment
    ADD CONSTRAINT uk_document_segment_order UNIQUE (document_version_id, segment_index);

ALTER TABLE document_segment
    ADD CONSTRAINT fk_document_segment_document FOREIGN KEY (document_id)
        REFERENCES knowledge_document (document_id);

ALTER TABLE document_segment
    ADD CONSTRAINT fk_document_segment_version FOREIGN KEY (document_version_id)
        REFERENCES document_version (document_version_id);

CREATE TABLE document_processing_task (
    id BIGINT NOT NULL PRIMARY KEY,
    document_id BIGINT NOT NULL,
    document_version_id BIGINT NOT NULL,
    previous_version_id BIGINT,
    previous_version VARCHAR(32),
    provider VARCHAR(32) NOT NULL DEFAULT 'mineru',
    provider_task_id VARCHAR(128),
    task_type VARCHAR(32) NOT NULL,
    chunk_id BIGINT,
    input_hash CHAR(64) NOT NULL,
    model_key VARCHAR(128),
    idempotency_key CHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    stage VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    next_poll_at TIMESTAMP,
    error_message VARCHAR(1000),
    lock_version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_processing_task_document FOREIGN KEY (document_id)
        REFERENCES knowledge_document (document_id),
    CONSTRAINT fk_processing_task_version FOREIGN KEY (document_version_id)
        REFERENCES document_version (document_version_id)
);

CREATE TABLE sys_user (
    id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    status TINYINT NOT NULL DEFAULT 1,
    last_login_at TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE sys_permission (
    id BIGINT NOT NULL PRIMARY KEY,
    permission VARCHAR(32) NOT NULL UNIQUE,
    status TINYINT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE sys_user_permission (
    id BIGINT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL,
    CONSTRAINT uk_user_permission UNIQUE (user_id, permission_id),
    CONSTRAINT fk_user_permission_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_user_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
);
