DROP TABLE IF EXISTS sys_user_permission;
DROP TABLE IF EXISTS sys_permission;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS document_segment;
DROP TABLE IF EXISTS document_version;
DROP TABLE IF EXISTS knowledge_document;

CREATE TABLE knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    document_name VARCHAR(255) NOT NULL,
    converted_document_name VARCHAR(255),
    document_path VARCHAR(1024),
    content CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'init',
    document_user BIGINT NOT NULL,
    document_type VARCHAR(64),
    segment_numbers INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE document_segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_version VARCHAR(64),
    chunk_id BIGINT,
    embedding_id BIGINT,
    skip_embedding TINYINT NOT NULL DEFAULT 0,
    segment_content CLOB NOT NULL,
    metadata CLOB,
    status VARCHAR(32) NOT NULL DEFAULT 'init',
    document_version_id BIGINT,
    version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version VARCHAR(64) NOT NULL,
    document_version_status VARCHAR(32) NOT NULL DEFAULT 'active',
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL,
    CONSTRAINT uk_document_version UNIQUE (document_id, version)
);

CREATE TABLE sys_user (
    id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    status TINYINT NOT NULL DEFAULT 1,
    last_login_at TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE sys_permission (
    id BIGINT NOT NULL PRIMARY KEY,
    permission VARCHAR(32) NOT NULL UNIQUE,
    status TINYINT NOT NULL DEFAULT 1,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL
);

CREATE TABLE sys_user_permission (
    id BIGINT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    create_by VARCHAR(64) NOT NULL,
    update_by VARCHAR(64) NOT NULL,
    CONSTRAINT uk_user_permission UNIQUE (user_id, permission_id),
    CONSTRAINT fk_user_permission_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_user_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
);
